version: '3'
services:
  nginx:
   container_name: v-nginx
   image: nginx:1.12.2
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d    
  app:
    restart: always
    build: ./webapp
    working_dir: /webapp
    volumes:
      - ./webapp:/webapp
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    
    